import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  addButton: {
    marginHorizontal: 15,
    marginBottom: 16,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    marginHorizontal: 15,
    marginBottom: 16,
    borderRadius: 20,
    padding: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F8B125',
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#888',
  },
  enderecoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFDF7',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F3E3B1',
  },
  cardLast: {
    marginBottom: 0,
  },
  enderecoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF6DE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  enderecoInfo: {
    flex: 1,
    marginRight: 8,
  },
  enderecoApelido: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
  },
  enderecoResumo: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
    lineHeight: 17,
  },
  enderecoCep: {
    fontSize: 11,
    color: '#888',
    marginTop: 4,
  },
  principalPill: {
    alignSelf: 'flex-start',
    marginTop: 8,
    backgroundColor: '#FFF6DE',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#F3E3B1',
  },
  enderecoPrincipal: {
    fontSize: 11,
    fontWeight: '700',
    color: '#F8B125',
  },
  emptyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF6DE',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },
  errorText: {
    color: '#D64545',
    fontSize: 14,
    textAlign: 'center',
  },
  retryText: {
    color: '#F8B125',
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
  },
});
